# Configuration for probot-no-response - https://github.com/probot/no-response

daysUntilClose: 30
responseRequiredLabel: question
closeComment: >
  This issue has been automatically closed because there has been no activity
  for quite some time now.
