language: elixir
services:
  - postgresql
elixir:
  - 1.10
otp_release:
  - 22.3
env:
  - MIX_ENV=test
  - ELIXIR_ASSERT_TIMEOUT=350
cache:
  directories:
    - deps
    - _build/
before_script:
  - psql -c 'create database teslamate_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix do deps.get, compile
script:
  - MIX_ENV=dev mix format --check-formatted
  - mix coveralls.travis
